//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public int IdArticulo { get; set; }
        public int CodigoArticulos { get; set; }
        public string Nombre { get; set; }
        public bool Estado { get; set; }
        public decimal costo { get; set; }
        public int CodigoProveedor { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
    }
}
